-- This file is used to import lua files during nvim start-up
require "vnmrd.options"
require "vnmrd.keymaps"
require "vnmrd.plugins"
require "vnmrd.colorscheme"
require "vnmrd.cmp"
require "vnmrd.lsp"
require "vnmrd.telescope"
require "vnmrd.treesitter"
require "vnmrd.dashboard"
